### ISSUE TITLE
Offline Installation Help

### ISSUE THREAD

**Issue by Peng-YM** [dzikoysk/Pandomium#20]
Hi, I want to use Pandomium in my server which cannot access the internet, I download the jar and the corresponding natives, when I run the test case, it throws the following error:
```
$ javac -cp ".:pandomium-67.0.jar" Browser.java
$  java -cp ".:pandomium-67.0.jar" Browser
```

```
[23:32:38.682][main/INFO ] #
[23:32:38.684][main/INFO ] # Launching Pandomium 67.0
[23:32:38.684][main/INFO ] # Chromium Version: 67.0.3396.62
[23:32:38.684][main/INFO ] # CEF Version: 3.3396.1775.g5340bb0
[23:32:38.684][main/INFO ] #
[23:32:38.685][main/INFO ] Progress: 0%
Exception in thread "main" java.lang.UnsatisfiedLinkError: no linuxenv in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at net.dzikoysk.linuxenv.LinuxJVMEnvironment.<init>(LinuxJVMEnvironment.java:6)
	at org.panda_lang.pandomium.loader.PandomiumLoaderWorker.load(PandomiumLoaderWorker.java:44)
	at org.panda_lang.pandomium.loader.PandomiumLoaderWorker.run(PandomiumLoaderWorker.java:24)
	at org.panda_lang.pandomium.loader.PandomiumLoader.load(PandomiumLoader.java:41)
	at org.panda_lang.pandomium.Pandomium.initialize(Pandomium.java:37)
	at Browser.main(Browser.java:14)
```
And Here's my file structure:
```
Browser.java
natives
pandomium-67.0.jar
```
Could you help me solve this issue, thanks!

**Comment by dzikoysk** [comment]
Looks like a bug with 67.0 natives archive. You should also download linuxenv.so from https://github.com/dzikoysk/LinuxEnv and then you should put in the natives directory.

**Comment by Peng-YM** [comment]
Thanks for your quick reply, another problem occurs:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: ~/JavaCEF/natives/libcef.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ~/JavaCEF/natives/libcef.so)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.cef.CefApp.<init>(CefApp.java:142)
	at org.cef.CefApp.getInstance(CefApp.java:213)
	at org.cef.CefApp.getInstance(CefApp.java:200)
	at org.panda_lang.pandomium.wrapper.PandomiumCEF.initialize(PandomiumCEF.java:16)
	at org.panda_lang.pandomium.Pandomium.lambda$initialize$0(Pandomium.java:34)
	at org.panda_lang.pandomium.loader.PandomiumLoader.callListeners(PandomiumLoader.java:56)
	at org.panda_lang.pandomium.loader.PandomiumLoaderWorker.load(PandomiumLoaderWorker.java:71)
	at org.panda_lang.pandomium.loader.PandomiumLoaderWorker.run(PandomiumLoaderWorker.java:24)
	at org.panda_lang.pandomium.loader.PandomiumLoader.load(PandomiumLoader.java:41)
	at org.panda_lang.pandomium.Pandomium.initialize(Pandomium.java:37)
	at Browser.main(Browser.java:14)
```

**Comment by comod** [comment]
> Looks like a bug with 67.0 natives archive. You should also download linuxenv.so from https://github.com/dzikoysk/LinuxEnv and then you should put in the natives directory.

Hey! I hvae the same Issue here
`Exception in thread "main" java.lang.UnsatisfiedLinkError: no linuxenv in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
`
and i cant find such a file. Where can i download linuxenv.so and where should i put into?

**Comment by dzikoysk** [comment]
@comod https://github.com/dzikoysk/linuxenv/releases

**Comment by comod** [comment]
Thanks, it works now!
