### ISSUE TITLE
Core dumped while running on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by Peng-YM** [dzikoysk/Pandomium#22]
When I'm trying to run the test under ubuntu 16.04, an error occurs:
```
java -cp .:pandomium-67.0.jar PandomiumTest
[17:43:00.768][main/INFO ] #
[17:43:00.770][main/INFO ] # Launching Pandomium 67.0
[17:43:00.770][main/INFO ] # Chromium Version: 67.0.3396.62
[17:43:00.770][main/INFO ] # CEF Version: 3.3396.1775.g5340bb0
[17:43:00.770][main/INFO ] #
[17:43:00.771][main/INFO ] Progress: 0%
[17:43:00.780][main/INFO ] Creating symlink /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/icudtl.dat to /home/charles/JCEF/natives/icudtl.dat
[17:43:00.780][main/INFO ] Creating symlink /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/natives_blob.bin to /home/charles/JCEF/natives/natives_blob.bin
[17:43:00.780][main/INFO ] Creating symlink /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/snapshot_blob.bin to /home/charles/JCEF/natives/snapshot_blob.bin
[17:43:00.781][main/INFO ] Progress: 100%
initialize on Thread[AWT-EventQueue-0,6,main] with library path /home/charles/JCEF/natives
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f10be5a5cda, pid=1198, tid=0x00007f10be79d700
#
# JRE version: OpenJDK Runtime Environment (8.0_171-b11) (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
# Java VM: OpenJDK 64-Bit Server VM (25.171-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [ld-linux-x86-64.so.2+0x9cda]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/charles/JCEF/hs_err_pid1198.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
[1]    1198 abort (core dumped)  java -cp .:pandomium-67.0.jar PandomiumTest
```
It works normally under windows.

**Comment by dzikoysk** [comment]
Yeah, you didn't use built-in loader, so you have to link some files manually:
https://github.com/dzikoysk/Pandomium/blob/37b444e693dbacd57e431ac30a521d088c681266/pandomium/src/main/java/org/panda_lang/pandomium/loader/PandomiumLoaderWorker.java#L50

Anyway, I think I can separate loader from linker in the future release.

**Comment by Peng-YM** [comment]
I already fixed the icu problem, since I had moved the folder to another place however the symlinks are not deleted, then ICU error happens, now symlinks can be create normally, but why still core dump?

**Comment by Peng-YM** [comment]
I think I did use the wrapper as you pointed out in stackoverflow (https://stackoverflow.com/questions/36609206/jcef-icu-check-failed)

**Comment by dzikoysk** [comment]
Damn it, I forgot about this in 67.0: 
* https://bitbucket.org/chromiumembedded/java-cef/issues/277/cannot-pack-jogl-all-natives-linux-in
I have to move jogl to the natives archive. I'll fix it tonight probably. If you don't want to wait, you can try to use old `Pandomium 1.0.6`, it should work.

**Comment by Peng-YM** [comment]
It's ok, currently I'm trying to port this library in Java Application, I will keep posting the problems I met here : )

**Comment by dzikoysk** [comment]
`67.0.1` should work

**Comment by Peng-YM** [comment]
Unfortunately, still buggy.
```
java -cp .:pandomium-67.0.1.jar PandomiumTest
[09:07:30.933][main/INFO ] #
[09:07:30.935][main/INFO ] # Launching Pandomium 67.0.1
[09:07:30.935][main/INFO ] # Chromium Version: 67.0.3396.62
[09:07:30.935][main/INFO ] # CEF Version: 3.3396.1775.g5340bb0
[09:07:30.935][main/INFO ] #
[09:07:30.936][main/INFO ] Progress: 0%
java.nio.file.FileAlreadyExistsException: /home/charles/JCEF/natives/libjogl_desktop.so
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at java.nio.file.Files.copy(Files.java:3016)
	at org.panda_lang.pandomium.loader.os.PandomiumLinuxNativesLoader.loadLinuxNatives(PandomiumLinuxNativesLoader.java:50)
	at org.panda_lang.pandomium.loader.PandomiumLoaderWorker.load(PandomiumLoaderWorker.java:42)
	at org.panda_lang.pandomium.loader.PandomiumLoaderWorker.run(PandomiumLoaderWorker.java:21)
	at org.panda_lang.pandomium.loader.PandomiumLoader.load(PandomiumLoader.java:41)
	at org.panda_lang.pandomium.Pandomium.initialize(Pandomium.java:37)
	at PandomiumTest.main(PandomiumTest.java:16)
Exception in thread "main" java.lang.RuntimeException: Pandomium is not initialized
	at org.panda_lang.pandomium.Pandomium.createClient(Pandomium.java:42)
	at PandomiumTest.main(PandomiumTest.java:18)
```

**Comment by Peng-YM** [comment]
After test on my machine, the version 1.0.6 with 1.0.4 native works fine under Ubuntu 16.04 LTS.

**Comment by dzikoysk** [comment]
Oops, I've made a typo:
https://github.com/dzikoysk/Pandomium/blob/3751bdf3d443d0cdfd7a3932a3a85337e82b528a/pandomium/src/main/java/org/panda_lang/pandomium/loader/os/PandomiumLinuxNativesLoader.java#L46

**Comment by Peng-YM** [comment]
I meet the same core dumped problem when I use the jar build by myself, you said that "I have to move jogl to natives archive", what does it mean? Here's my native folder(also compile by myself)
![](https://ws1.sinaimg.cn/large/c2dfc71dgy1ftu7af5qf2j20lj09tmxt.jpg).

And I think these line in build script already packed jogl into jcef-linux.jar.
```
# Create fat jar
mkdir jcef-linux64
(cd jcef-linux64; unzip -uo ../gluegen-rt.jar)
(cd jcef-linux64; unzip -uo ../gluegen-rt-natives-linux-amd64.jar)
(cd jcef-linux64; unzip -uo ../jcef.jar)
(cd jcef-linux64; unzip -uo ../jogl-all.jar)
(cd jcef-linux64; unzip -uo ../jogl-all-natives-linux-amd64.jar)
jar -cvf jcef-linux64.jar -C jcef-linux64 .
```

**Comment by dzikoysk** [comment]
Nah, I have no idea what's wrong with that. This system is so unfriendly. It's a problem with `libGL.so` and:

https://github.com/sgothel/gluegen/blob/99b357956e4fd516ddd051d8a0f478c47faa40b1/src/java/jogamp/common/os/UnixDynamicLinkerImpl.java#L45

**Comment by dzikoysk** [comment]
I know, it affacts linux natives 67.0+. Building and debugging that takes so much time and the wheater is awful. I'll play with that a little bit later

**Comment by dzikoysk** [comment]
Did you solve that?
