### ISSUE TITLE
Unsupported class version number [53.0] (maximum 52.0, Java 1.8)

### ISSUE THREAD

**Issue by testwen00** [dzikoysk/Pandomium#31]
[proguard] java.io.IOException: Can't read [C:\Users\wen\.m2\repository\org\panda-lang\pandomium\67.0.3\pandomium-67.0.3.jar] (Can't process class [META-INF/versions/9/module-info.class] (Unsupported class version number [53.0] (maximum 52.0, Java 1.8)))
 [proguard] 	at proguard.InputReader.readInput(InputReader.java:188)
 [proguard] 	at proguard.InputReader.readInput(InputReader.java:158)
 [proguard] 	at proguard.InputReader.readInput(InputReader.java:136)
 [proguard] 	at proguard.InputReader.execute(InputReader.java:88)
 [proguard] 	at proguard.ProGuard.readInput(ProGuard.java:218)
 [proguard] 	at proguard.ProGuard.execute(ProGuard.java:82)
 [proguard] 	at proguard.ProGuard.main(ProGuard.java:538)

**Comment by testwen00** [comment]
i solved it.
update proguard new version to 6.0.3
  <dependency>
                    <groupId>net.sf.proguard</groupId>
                    <artifactId>proguard-base</artifactId>
                    <version>6.0.3</version>
</dependency>
