### ISSUE TITLE
Native Library jawt.dll already loaded in another classloader

### ISSUE THREAD

**Issue by ForsakenHarmony** [dzikoysk/Pandomium#39]
I'm trying to write a plugin for IDEA which integrates chromium as a webview, not sure if this error is on me, but any help would be appreciated

```
java.lang.UnsatisfiedLinkError: Native Library C:\Users\harmony\.gradle\caches\modules-2\files-2.1\com.jetbrains\jbre\jbrex8u152b1343.15_windows_x64\jre\bin\jawt.dll already loaded in another classloader
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1907)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1845)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.cef.CefApp.<init>(CefApp.java:138)
	at org.cef.CefApp.getInstance(CefApp.java:213)
	at org.cef.CefApp.getInstance(CefApp.java:200)
	at org.panda_lang.pandomium.wrapper.PandomiumCEF.initialize(PandomiumCEF.java:16)
	at org.panda_lang.pandomium.Pandomium.lambda$initialize$0(Pandomium.java:34)
	at org.panda_lang.pandomium.loader.PandomiumLoader.callListeners(PandomiumLoader.java:56)
	at org.panda_lang.pandomium.loader.PandomiumLoaderWorker.load(PandomiumLoaderWorker.java:46)
	at org.panda_lang.pandomium.loader.PandomiumLoaderWorker.run(PandomiumLoaderWorker.java:21)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ForsakenHarmony** [comment]
@dzikoysk any ideas?

**Comment by dzikoysk** [comment]
Here's the cause:
https://bitbucket.org/chromiumembedded/java-cef/src/d64cd6c266d5a9fc485bdfb6d5b672201dc5dfc7/java/org/cef/CefApp.java?at=master#lines-138

Pandomium is not modifying sources, so I'm not able to fix that. You should ask for optional loading of libraries here:
https://bitbucket.org/chromiumembedded/java-cef/issues

**Comment by ForsakenHarmony** [comment]
https://bitbucket.org/chromiumembedded/java-cef/issues/317/native-library-jawtdll-already-loaded-in

if anyone else runs across this

**Comment by dzikoysk** [comment]
Voted :)
