### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by stefaneidelloth** [dzikoysk/Pandomium#52]
When I try to start the full example I get

```
[11:58:03.958][main/INFO ] #
[11:58:03.961][main/INFO ] # Launching Pandomium 67.0.6
[11:58:03.961][main/INFO ] # Chromium Version: 67.0.3396.62
[11:58:03.961][main/INFO ] # CEF Version: 3.3396.1775.g5340bb0
[11:58:03.962][main/INFO ] #
[11:58:03.963][main/INFO ] Progress: 0%
[11:58:03.964][main/INFO ] Progress: 5%
[11:58:03.966][main/INFO ] Progress: 10%
[11:58:05.543][main/INFO ] Starting to download <unknown size> MB of data
[11:58:05.543][main/INFO ] Downloading https://pandomium.panda-lang.org/download/natives/67.0/win64-natives.tar.xz
java.net.ConnectException: Connection refused: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:285)
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1075)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:163)
	at org.panda_lang.pandomium.loader.PandomiumDownloader.download(PandomiumDownloader.java:20)
	at org.panda_lang.pandomium.loader.PandomiumNativesLoader.loadNatives(PandomiumNativesLoader.java:41)
	at org.panda_lang.pandomium.loader.PandomiumLoaderWorker.load(PandomiumLoaderWorker.java:31)
	at org.panda_lang.pandomium.loader.PandomiumLoaderWorker.run(PandomiumLoaderWorker.java:21)
	at org.panda_lang.pandomium.loader.PandomiumLoader.load(PandomiumLoader.java:41)
	at org.panda_lang.pandomium.Pandomium.initialize(Pandomium.java:37)
	at swtDemo.Main.main(Main.java:21)
Exception in thread "main" java.lang.RuntimeException: Pandomium is not initialized
	at org.panda_lang.pandomium.Pandomium.createClient(Pandomium.java:42)
	at swtDemo.Main.main(Main.java:23)
```

Can I configure some proxy settings for Pandomium?

**Comment by dzikoysk** [comment]
You should provide your proxy settings for Java: https://stackoverflow.com/a/8422570/3426515, because Pandomium just uses default URLConnection to download natives.

Pandomium builder has also support for proxy in JCEF: https://github.com/dzikoysk/Pandomium/issues/32

**Comment by stefaneidelloth** [comment]
Thank you. That did not work for me. I  used a different internet connection.
