### ISSUE TITLE
Pandomium is not initialized yet

### ISSUE THREAD

**Issue by scaventz** [dzikoysk/pandomium#85]
I'm working on a Windows11 machine, I tried both maven & gradle, tried ~~java8~~/java11/java17, got into the same exception.

full stack trace is
```
D:\IDE\Java\openjdk11\bin\java.exe "-javaagent:D:\IDE\JetBrains\IntelliJ IDEA Community Edition 2021.2\lib\idea_rt.jar=14642:D:\IDE\JetBrains\IntelliJ IDEA Community Edition 2021.2\bin" -Dfile.encoding=UTF-8 -classpath D:\ReposMine\NorthLight\target\classes;C:\Users\scave\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib-jdk8\1.6.10\kotlin-stdlib-jdk8-1.6.10.jar;C:\Users\scave\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib\1.6.10\kotlin-stdlib-1.6.10.jar;C:\Users\scave\.m2\repository\org\jetbrains\annotations\13.0\annotations-13.0.jar;C:\Users\scave\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib-common\1.6.10\kotlin-stdlib-common-1.6.10.jar;C:\Users\scave\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib-jdk7\1.6.10\kotlin-stdlib-jdk7-1.6.10.jar;C:\Users\scave\.m2\repository\org\panda-lang\pandomium\1.1.3-JCEF-v1.0.10-84.3.8+gc8a556f+chromium-84.0.4147.105\pandomium-1.1.3-JCEF-v1.0.10-84.3.8+gc8a556f+chromium-84.0.4147.105.jar;C:\Users\scave\.m2\repository\org\panda-lang\panda\0.5.0-alpha\panda-0.5.0-alpha.jar;C:\Users\scave\.m2\repository\org\panda-lang\panda-framework\0.5.0-alpha\panda-framework-0.5.0-alpha.jar;C:\Users\scave\.m2\repository\org\panda-lang\panda-utilities\0.5.0-alpha\panda-utilities-0.5.0-alpha.jar;C:\Users\scave\.m2\repository\org\javassist\javassist\3.28.0-GA\javassist-3.28.0-GA.jar;C:\Users\scave\.m2\repository\net\dzikoysk\cdn\1.12.3\cdn-1.12.3.jar;C:\Users\scave\.m2\repository\org\panda-lang\expressible\1.1.1\expressible-1.1.1.jar;C:\Users\scave\.m2\repository\net\dzikoysk\linuxenv\1.0.0\linuxenv-1.0.0.jar;C:\Users\scave\.m2\repository\com\squareup\okhttp3\okhttp\5.0.0-alpha.2\okhttp-5.0.0-alpha.2.jar;C:\Users\scave\.m2\repository\com\squareup\okio\okio\2.9.0\okio-2.9.0.jar;C:\Users\scave\.m2\repository\com\google\code\gson\gson\2.8.9\gson-2.8.9.jar;C:\Users\scave\.m2\repository\org\apache\commons\commons-compress\1.21\commons-compress-1.21.jar;C:\Users\scave\.m2\repository\org\tukaani\xz\1.6\xz-1.6.jar;C:\Users\scave\.m2\repository\net\dzikoysk\dynamic-logger\1.0.3\dynamic-logger-1.0.3.jar;C:\Users\scave\.m2\repository\org\panda-lang\pandomium-fat-jars\jcef-win32-fat\1.1.3-JCEF-v1.0.10-84.3.8+gc8a556f+chromium-84.0.4147.105\jcef-win32-fat-1.1.3-JCEF-v1.0.10-84.3.8+gc8a556f+chromium-84.0.4147.105.jar;C:\Users\scave\.m2\repository\org\panda-lang\pandomium-fat-jars\jcef-win64-fat\1.1.3-JCEF-v1.0.10-84.3.8+gc8a556f+chromium-84.0.4147.105\jcef-win64-fat-1.1.3-JCEF-v1.0.10-84.3.8+gc8a556f+chromium-84.0.4147.105.jar Main
# 
# Launching Pandonium v1.1.3-JCEF-v1.0.10-84.3.8+gc8a556f+chromium-84.0.4147.105
# Determined 'AMD64' as operating systems architecture.
# Determined 'WINDOWS' as operating system.
# 
Progress: 0%
Progress: 100%
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.panda_lang.pandomium.util.SystemUtils (file:/C:/Users/scave/.m2/repository/org/panda-lang/pandomium/1.1.3-JCEF-v1.0.10-84.3.8+gc8a556f+chromium-84.0.4147.105/pandomium-1.1.3-JCEF-v1.0.10-84.3.8+gc8a556f+chromium-84.0.4147.105.jar) to field java.lang.ClassLoader.sys_paths
WARNING: Please consider reporting this to the maintainers of org.panda_lang.pandomium.util.SystemUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Failed to install JCEF natives update. Message: null
java.lang.NullPointerException
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2646)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at org.cef.SystemBootstrap$1.loadLibrary(SystemBootstrap.java:24)
	at org.cef.SystemBootstrap.loadLibrary(SystemBootstrap.java:36)
	at org.cef.CefApp.<init>(CefApp.java:144)
	at org.cef.CefApp.getInstance(CefApp.java:221)
	at org.panda_lang.pandomium.Pandomium.lambda$new$0(Pandomium.java:80)
	at org.panda_lang.pandomium.loader.PandomiumLoader.callListeners(PandomiumLoader.java:69)
	at org.panda_lang.pandomium.loader.PandomiumLoader.load(PandomiumLoader.java:55)
	at org.panda_lang.pandomium.Pandomium.<init>(Pandomium.java:83)
	at org.panda_lang.pandomium.PandomiumBuilder.build(PandomiumBuilder.java:52)
	at org.panda_lang.pandomium.Pandomium.buildDefault(Pandomium.java:52)
	at Main.main(Main.java:7)
Exception in thread "main" java.lang.RuntimeException: Pandomium is not initialized yet!
	at org.panda_lang.pandomium.Pandomium.createClient(Pandomium.java:102)
	at org.panda_lang.pandomium.Pandomium.createClient(Pandomium.java:91)
	at Main.main(Main.java:7)

Process finished with exit code 1

```

Also what worth to mention is that I live in an area that is not friendly to the Internet, access to websites like github and google is not stable, so maybe the dependency package I downloaded is incomplete? I don't know.

Here is my reproducer (using maven): 
https://github.com/scaventz/reproducer-issue-of-pandomium.git

**Comment by dzikoysk** [comment]
Hello :) I'm able to launch this with clean setup on JDK11 & 8 (15/16/17 is not supported due to changes in reflections & class loaders):

![image](https://user-images.githubusercontent.com/4235722/146930049-277452d5-a623-433b-9fd9-160f3dfdd821.png)

What's your JDK version (build number) and which distribution it is? (Oracle/Adoptium/Bellsoft/etc.)

**Comment by scaventz** [comment]
Thanks for your response! I tried again with JDK11, still got same error.
```
D:\IDE\Java\openjdk11\bin>java -version
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9+11, mixed mode)
```

I have encountered errors caused by incomplete zip packages before, so I am worried that it is a problem with my network. Will try to check that later.

**Comment by scaventz** [comment]
Apologise first, it works on JDK8, I guess I did not configure it correctly yesterday.

As for JDK11, It seems to be related to AdoptOpenJDK issue , see comment [here](https://github.com/adoptium/adoptium-support/issues/83#issuecomment-622928516).
![1640154866(1)](https://user-images.githubusercontent.com/5899940/147046752-3e751f0e-edf2-4a5b-997a-df110ab1dd79.png)

**Comment by dzikoysk** [comment]
Yeah, that's why I was asking about the distribution, these builds may differ under the hood and work slightly different. Let's try to use this init method :)

**Comment by dzikoysk** [comment]
Try to use 1.1.4 and let me know if it works :)

* https://github.com/dzikoysk/pandomium/releases

**Comment by scaventz** [comment]
Just tired the new version, it works for my `AdoptOpenJDK 11` . 👍
